import { LegalPage } from "@/components/LegalPage";
import { pageMeta } from "@/lib/seo";
import { CONTACT_EMAIL } from "@/lib/site";

export const metadata = pageMeta({
  title: "Privacy",
  description:
    "What Universal Studios Hotels does and does not collect: no accounts, no analytics, no cookies set by this site, and what happens when you email us.",
  path: "/privacy",
  keywords: ["privacy policy"],
});

export default function Page() {
  return (
    <LegalPage
      title="Privacy"
      path="/privacy"
      updated="2026-10-02"
      intro="This site collects nothing about you. There are no accounts, no analytics and no cookies set by us."
    >
      <h2>What we collect</h2>
      <p>
        Nothing, as the site stands. There is no sign-up, no contact form, no
        newsletter, no analytics script and no advertising script. We set no
        cookies and use no browser storage, which is why you have not been asked
        to consent to any.
      </p>

      <h2>If you email us</h2>
      <p>
        Your message and address sit in our mailbox so we can reply and keep a
        record of what was agreed about a listing. We do not add you to a
        mailing list and we do not pass your details to anyone else. Ask us to
        delete the correspondence and we will.
      </p>

      <h2>Hosting</h2>
      <p>
        The site is hosted by Vercel, which keeps standard server logs including
        IP addresses for security and abuse prevention. Those logs are
        Vercel&rsquo;s, generated by the act of serving the page, and we do not
        use them to build any profile of you.
      </p>

      <h2>Links to other sites</h2>
      <p>
        Following a link to Booking.com or to a property&rsquo;s own site takes
        you under that company&rsquo;s privacy policy, not ours. Booking.com in
        particular will set its own cookies, including ones that record that you
        arrived from here — that is how the affiliate commission described on
        our <a href="/affiliate-disclosure">affiliate disclosure</a> page is
        attributed. We never see who you are; we only ever see totals.
      </p>

      <h2>Your rights</h2>
      <p>
        Under UK GDPR you can ask what we hold about you, ask for it to be
        corrected or deleted, and complain to the Information
        Commissioner&rsquo;s Office. In practice the only thing we are ever
        likely to hold is an email you sent us. Write to{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Changes</h2>
      <p>
        If the site starts collecting anything — analytics, say — this page gets
        updated before that goes live, and the review date above changes with
        it.
      </p>
    </LegalPage>
  );
}
